services:
  fcra:
    image: working-fcra:v1
#   build:
#     context: .
#     dockerfile: Dockerfile.fcra
    network_mode: bridge
    ports:
#     - "8080:8180"
      - "3838:8180"
    container_name: fcra-app
    pull_policy: always
    tty: true
    restart: unless-stopped
  ollama:
#   image: shiny_dev-ollama:v1
#   image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    build:
      context: .
      dockerfile: Dockerfile.ollama
    network_mode: bridge
#   network_mode: host
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped

  open-webui:
    build:
      context: .
#     args:
#       OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile.webui
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    network_mode: bridge
#   network_mode: host
    ports:
      - 3000:8080
#     - 8190:8190
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
#           - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
#     - 'OLLAMA_BASE_URL=http://127.0.0.1:11434'
#           - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
#                 - 'WEBUI_SECRET_KEY='
#                     extra_hosts:
#                           - host.docker.internal:host-gateway
#                               restart: unless-stopped
volumes:
  ollama: {}
  open-webui: {}
